### Listar desenvolvedores
GET http://localhost:3000/developers

### Get desenvolvedor
GET  http://localhost:3000/developers/1

### Criar desenvolvedor
POST http://localhost:3000/developers
Content-Type: application/json

{
    "nome": "Genius",
    "email": "guilherme@gmail.com",
    "cpf": "524.157.278-30"
}

### Update desenvolvedor
PATCH http://localhost:3000/developers/1

### Delete desenvolvedor
DELETE http://localhost:3000/developers/1
